@groupId=66b3b776f81fe2f7f3009179

### Add Dinner
POST {{sgdApiHost}}/Dinner
Content-Type: application/json
Authorization: Bearer {{$auth.token("api")}}

{
    "name": "Mexican Fiesta",
    "date": "2024-08-23T19:30:00Z",
    "description": "Join us for a night of tacos, nachos, and margaritas.",
    "groupId": "{{groupId}}",
    "capacity": 11,
    "signUpMethod": "Lottery",
    "randomSelectionTime": "2024-08-19T19:30:00Z",
    "imageUrl": "https://example.com/images/mexican_fiesta.png"
  }