### Add Group
POST {{sgdApiHost}}/Group
Content-Type: application/json
Authorization: Bearer {{$auth.token("api")}}

{
  "name": "MMM 26",
  "description": "MMMs Graduating in 2026",
  "isOpen": true
}