@groupId=66ac495917004b18d8c7d506

### Add Dinner
POST {{sgdApiHost}}/Dinner
Content-Type: application/json
Authorization: Bearer {{$auth.token("api")}}

{
  "name": "Gourmet Dinner",
  "date": "2024-10-10T19:00:00Z",
  "description": "A gourmet dinner with a lottery sign-up.",
  "groupId": "{{groupId}}",
  "capacity": 20,
  "signUpMethod": "Lottery",
  "randomSelectionTime": "2024-10-01T12:00:00Z",
  "imageUrl": "https://example.com/images/gourmet_dinner.png"
}